insert into duoshouji.tag (name, is_chanel, sort_order) values ('男人装', 1, 1);
insert into duoshouji.tag (name, is_chanel, sort_order) values ('美人志', 1, 2);
insert into duoshouji.tag (name, is_chanel, sort_order) values ('宝贝书', 1, 3);
insert into duoshouji.tag (name, is_chanel, sort_order) values ('吃货说', 1, 4);

insert into duoshouji.category (category_id, category_name, is_tag, is_channel) values (10000000, '女装男装', 0, 0);
insert into duoshouji.category (category_id, category_name, is_tag, is_channel) values (20000000, '鞋类箱包', 0, 0);
insert into duoshouji.category (category_id, category_name, is_tag, is_channel) values (30000000, '母婴用品', 0, 0);
insert into duoshouji.category (category_id, category_name, is_tag, is_channel) values (40000000, '护肤彩妆', 0, 0);
insert into duoshouji.category (category_id, category_name, is_tag, is_channel) values (50000000, '汇吃美食', 0, 0);
insert into duoshouji.category (category_id, category_name, is_tag, is_channel) values (60000000, '珠宝配饰', 0, 0);
insert into duoshouji.category (category_id, category_name, is_tag, is_channel) values (70000000, '家装建材', 0, 0);
insert into duoshouji.category (category_id, category_name, is_tag, is_channel) values (80000000, '家居家纺', 0, 0);
insert into duoshouji.category (category_id, category_name, is_tag, is_channel) values (90000000, '百货市场', 0, 0);
insert into duoshouji.category (category_id, category_name, is_tag, is_channel) values (10000000, '汽车用品', 0, 0);
insert into duoshouji.category (category_id, category_name, is_tag, is_channel) values (11000000, '手机数码', 0, 0);
insert into duoshouji.category (category_id, category_name, is_tag, is_channel) values (12000000, '家电办公', 0, 0);
insert into duoshouji.category (category_id, category_name, is_tag, is_channel) values (13000000, '更多服务', 0, 0);
insert into duoshouji.category (category_id, category_name, is_tag, is_channel) values (14000000, '生活服务', 0, 0);
insert into duoshouji.category (category_id, category_name, is_tag, is_channel) values (15000000, '运动户外', 0, 0);
insert into duoshouji.category (category_id, category_name, is_tag, is_channel) values (16000000, '花鸟文娱', 0, 0);
insert into duoshouji.category (category_id, category_name, is_tag, is_channel) values (17000000, '农资采购', 0, 0);

insert into duoshouji.brand (brand_id, brand_name, is_tag, is_channel) values (3000000000001, '路易威登', 0, 0);
insert into duoshouji.brand (brand_id, brand_name, is_tag, is_channel) values (3000000000002, '爱马仕', 0, 0);
insert into duoshouji.brand (brand_id, brand_name, is_tag, is_channel) values (3000000000003, '古驰', 0, 0);
insert into duoshouji.brand (brand_id, brand_name, is_tag, is_channel) values (3000000000004, '香奈儿', 0, 0);
insert into duoshouji.brand (brand_id, brand_name, is_tag, is_channel) values (3000000000005, '轩尼诗', 0, 0);
insert into duoshouji.brand (brand_id, brand_name, is_tag, is_channel) values (3000000000006, '劳力士', 0, 0);
insert into duoshouji.brand (brand_id, brand_name, is_tag, is_channel) values (3000000000007, '酩悦香槟', 0, 0);
insert into duoshouji.brand (brand_id, brand_name, is_tag, is_channel) values (3000000000008, '卡地亚', 0, 0);
insert into duoshouji.brand (brand_id, brand_name, is_tag, is_channel) values (3000000000009, '芬迪', 0, 0);
